import { ColorScheme } from '../components';

export const light: ColorScheme = {
  primary: '#d1d6e2',
  secondary: '#636a7e',
  tertiary: '#bfc6d6',
  background: '#f0f3f8',
  backgroundSecondary: '#ffffff',
  buttonPrimary: '#2B2835',
  buttonPrimaryHover: '#4B4759',
  buttonPrimaryText: '#ffffff',
  buttonPrimaryTextHover: '#f5f5f5',
  buttonSecondary: '#d2cfdb',
  buttonSecondaryHover: '#f8f6fd',
  buttonSecondaryText: '#7f7d83',
  buttonSecondaryTextHover: '#17141b',
  textPrimary: '#121419',
  textSecondary: '#161921',
  textPrimaryHover: '#000000',
  textSecondaryHover: '#000000',
  inputPrimaryBackground: '#ffffff',
  inputPrimaryText: '#000000',
  inputPrimaryPlaceholder: '#a9afbe',
  inputPrimaryBorder: '#a9afbe',
  inputSecondaryBackground: '#dee1e9',
  inputSecondaryText: '#000000',
  inputSecondaryPlaceholder: '#a9afbe',
  inputSecondaryBorder: '#a9afbe',
  success: '#97c597',
  error: '#e57878',
  warning: '#dfdf3a',
  info: '#7c7cfd',
};

export const dark: ColorScheme = {
  primary: '#424650',
  secondary: '#242831',
  tertiary: '#5c606a',
  background: '#485165',
  backgroundSecondary: '#494f5b',
  buttonPrimary: '#d4d2de',
  buttonPrimaryHover: '#ada8bd',
  buttonPrimaryText: '#3b3b3b',
  buttonPrimaryTextHover: '#3c3c3c',
  buttonSecondary: '#2b2835',
  buttonSecondaryHover: '#4b4759',
  buttonSecondaryText: '#c0c0cb',
  buttonSecondaryTextHover: '#ffffff',
  textPrimary: '#dadada',
  textSecondary: '#a9afbe',
  textPrimaryHover: '#ffffff',
  textSecondaryHover: '#ffffff',
  inputPrimaryBackground: '#545965',
  inputPrimaryText: '#ffffff',
  inputPrimaryPlaceholder: '#a9afbe',
  inputPrimaryBorder: '#a9afbe',
  inputSecondaryBackground: '#636a7e',
  inputSecondaryText: '#ffffff',
  inputSecondaryPlaceholder: '#a9afbe',
  inputSecondaryBorder: '#a9afbe',
  success: '#98e298',
  error: '#ff6565',
  warning: '#ffff4c',
  info: '#9b9bff',
};
